### ha-sRNA d/a expression pattern analysis
mkdir -p ${EXP7_PATH}/expression_pattern_analysis

java -jar ${TOOL_EXPRESSION_PATTERN} -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} -associatedSequencesFilename ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv -differentialExpressionTest yes > ${EXP7_PATH}/expression_pattern_analysis/pos_hasrna_expression_pattern.csv
java -jar ${TOOL_EXPRESSION_PATTERN} -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} -associatedSequencesFilename ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv -differentialExpressionTest yes > ${EXP7_PATH}/expression_pattern_analysis/neg_hasrna_expression_pattern.csv

### ha-sRNA length distribution enrichment analysis
mkdir -p ${EXP7_PATH}/length_analysis

java -jar ${TOOL_SRNA_LENGTH} -bootstrap 1000 -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} -filename ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv > ${EXP7_PATH}/srna_length_analysis/pos_hasrna_length_enrichment.csv
java -jar ${TOOL_SRNA_LENGTH} -bootstrap 1000 -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} -filename ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv > ${EXP7_PATH}/srna_length_analysis/neg_hasrna_length_enrichment.csv

### ha-sRNA mapping count analysis
mkdir -p ${EXP7_PATH}/mapping_count_analysis

java -jar ${TOOL_SRNA_MAPPING_COUNT} -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} -fileName ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv > ${EXP7_PATH}/mapping_count_analysis/pos_hasrna_mapping_count.csv
java -jar ${TOOL_SRNA_MAPPING_COUNT} -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} -fileName ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv > ${EXP7_PATH}/mapping_count_analysis/neg_hasrna_mapping_count.csv

### ha-sRNA annotation mapping analysis
mkdir -p ${EXP7_PATH}/annotation/mapping
mkdir -p ${EXP7_PATH}/annotation/type
mkdir -p ${EXP7_PATH}/annotation/specific
mkdir -p ${EXP7_PATH}/annotation/intersect
mkdir -p ${EXP7_PATH}/annotation/summary

java -jar ${TOOL_ANNOTATION_CLUSTER} -sRNAFilename data/mph_gy_positive_indices.csv  -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_positive_associated_srna_annotation_summary.csv
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -annotation gene -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_positive_associated_srna_annotation_gene_summary.csv
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -annotation intergenic -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_positive_associated_srna_annotation_intergenic_summary.csv
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -annotation repeat -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_positive_associated_srna_annotation_repeat_summary.csv
java -jar ${TOOL_ANNOTATION_SPECIFIC} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -annotation gene -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/specific/mph_gy_positive_associated_srna_annotation_specific_gene_summary.csv
java -jar ${TOOL_ANNOTATION_SPECIFIC} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -annotation intergenic -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/specific/mph_gy_positive_associated_srna_annotation_specific_intergenic_summary.csv
java -jar ${TOOL_ANNOTATION_SPECIFIC} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_positive_associated_srna_annotation.txt -annotation repeat -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/specific/mph_gy_positive_associated_srna_annotation_specific_repeat_summary.csv
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect gene,repeat -geneFile results/annotation_type/mph_gy_positive_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_positive_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_positive_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_positive_gene_repeat_summary.csv &
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect gene,intergenic -geneFile results/annotation_type/mph_gy_positive_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_positive_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_positive_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_positive_gene_intergenic_summary.csv &
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect repeat,intergenic -geneFile results/annotation_type/mph_gy_positive_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_positive_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_positive_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_positive_repeat_intergenic_summary.csv &
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect gene,repeat,intergenic -geneFile results/annotation_type/mph_gy_positive_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_positive_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_positive_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_positive_gene_repeat_intergenic_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene -result ${EXP7_PATH}/annotation/specific/mph_gy_positive_associated_srna_annotation_specific_gene_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_length_summary.csv 
java -jar ${TOOL_ANNOTATION_SUMMARY} -title intergenic -result ${EXP7_PATH}/annotation/specific/mph_gy_positive_associated_srna_annotation_specific_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_intergenic_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title repeat -result ${EXP7_PATH}/annotation/specific/mph_gy_positive_associated_srna_annotation_specific_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_repeat_length_summary.csv 
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene/intergenic -result ${EXP7_PATH}/annotation/intersect/mph_gy_positive_gene_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_intergenic_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene/repeat -result ${EXP7_PATH}/annotation/intersect/mph_gy_positive_gene_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_repeat_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title repeat/intergenic -result ${EXP7_PATH}/annotation/intersect/mph_gy_positive_repeat_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_repeat_intergenic_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene/repeat/intergenic -result ${EXP7_PATH}/annotation/intersect/mph_gy_positive_gene_repeat_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD}  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_repeat_intergenic_length_summary.csv
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_positive_intergenic_length_summary.csv | cat ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_length_summary.csv -  > temp1
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_positive_repeat_length_summary.csv | cat temp1 -  > temp2
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_intergenic_length_summary.csv | cat temp2 -  > temp3
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_repeat_length_summary.csv | cat temp3 -  > temp4
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_positive_repeat_intergenic_length_summary.csv | cat temp4 -  > temp5
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_positive_gene_repeat_intergenic_length_summary.csv | cat temp5 -  > ${EXP7_PATH}/annotation/summary/mph_gy_positive_summary.csv
rm -f temp*

java -jar ${TOOL_ANNOTATION_CLUSTER} -sRNAFilename data/mph_gy_negative_indices.csv  -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_negative_associated_srna_annotation_summary.csv
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -annotation gene -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_negative_associated_srna_annotation_gene_summary.csv
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -annotation intergenic -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_negative_associated_srna_annotation_intergenic_summary.csv
java -jar ${TOOL_ANNOTATION_ANALYSIS} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -annotation repeat -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/type/mph_gy_negative_associated_srna_annotation_repeat_summary.csv
java -jar ${TOOL_ANNOTATION_SPECIFIC} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -annotation gene -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/specific/mph_gy_negative_associated_srna_annotation_specific_gene_summary.csv
java -jar ${TOOL_ANNOTATION_SPECIFIC} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -annotation intergenic -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/specific/mph_gy_negative_associated_srna_annotation_specific_intergenic_summary.csv
java -jar ${TOOL_ANNOTATION_SPECIFIC} -filename  ${EXP7_PATH}/annotation/mapping/mph_gy_negative_associated_srna_annotation.txt -annotation repeat -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/specific/mph_gy_negative_associated_srna_annotation_specific_repeat_summary.csv
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect gene,repeat -geneFile results/annotation_type/mph_gy_negative_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_negative_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_negative_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_negative_gene_repeat_summary.csv &
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect gene,intergenic -geneFile results/annotation_type/mph_gy_negative_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_negative_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_negative_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_negative_gene_intergenic_summary.csv &
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect repeat,intergenic -geneFile results/annotation_type/mph_gy_negative_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_negative_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_negative_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_negative_repeat_intergenic_summary.csv &
java -jar ${TOOL_ANNOTATION_INTERSECT} -intersect gene,repeat,intergenic -geneFile results/annotation_type/mph_gy_negative_associated_srna_annotation_gene_summary.csv -intergenicFile results/annotation_type/mph_gy_negative_associated_srna_annotation_intergenic_summary.csv -repeatFile results/annotation_type/mph_gy_negative_associated_srna_annotation_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/intersect/mph_gy_negative_gene_repeat_intergenic_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene -result ${EXP7_PATH}/annotation/specific/mph_gy_negative_associated_srna_annotation_specific_gene_summary.csv > ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title intergenic -result ${EXP7_PATH}/annotation/specific/mph_gy_negative_associated_srna_annotation_specific_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/summary/mph_gy_negative_intergenic_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title repeat -result ${EXP7_PATH}/annotation/specific/mph_gy_negative_associated_srna_annotation_specific_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/summary/mph_gy_negative_repeat_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene/intergenic -result ${EXP7_PATH}/annotation/intersect/mph_gy_negative_gene_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_intergenic_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene/repeat -result ${EXP7_PATH}/annotation/intersect/mph_gy_negative_gene_repeat_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_repeat_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title repeat/intergenic -result ${EXP7_PATH}/annotation/intersect/mph_gy_negative_repeat_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/summary/mph_gy_negative_repeat_intergenic_length_summary.csv
java -jar ${TOOL_ANNOTATION_SUMMARY} -title gene/repeat/intergenic -result ${EXP7_PATH}/annotation/intersect/mph_gy_negative_gene_repeat_intergenic_summary.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_repeat_intergenic_length_summary.csv
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_negative_intergenic_length_summary.csv | cat ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_length_summary.csv -  > temp1
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_negative_repeat_length_summary.csv | cat temp1 -  > temp2
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_intergenic_length_summary.csv | cat temp2 -  > temp3
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_repeat_length_summary.csv | cat temp3 -  > temp4
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_negative_repeat_intergenic_length_summary.csv | cat temp4 -  > temp5
tail -n1 ${EXP7_PATH}/annotation/summary/mph_gy_negative_gene_repeat_intergenic_length_summary.csv | cat temp5 -  > ${EXP7_PATH}/annotation/summary/mph_gy_negative_summary.csv
rm -f temp*

### ha-sRNA repetitive element enrichtment/depletion analysis
mkdir -p ${EXP7_PATH}/repeat_enrichment

java -jar ${TOOL_REPEAT_ENRICHMENT} -bootstrap 1000 -classification super -filename ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/repeat_enrichment/mph_gy_repeat_super_family_bootstrap_1000_positive_associated_results.csv
java -jar ${TOOL_REPEAT_ENRICHMENT} -bootstrap 1000 -classification family -filename ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/repeat_enrichment/mph_gy_repeat_family_bootstrap_1000_positive_associated_results.csv

java -jar ${TOOL_REPEAT_ENRICHMENT} -bootstrap 1000 -classification super -filename ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/repeat_enrichment/mph_gy_repeat_super_family_bootstrap_1000_negative_associated_results.csv
java -jar ${TOOL_REPEAT_ENRICHMENT} -bootstrap 1000 -classification family -filename ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv -databaseUser ${DATABASE_USER} -databasePassword ${DATABASE_PASSWORD} > ${EXP7_PATH}/repeat_enrichment/mph_gy_repeat_family_bootstrap_1000_negative_associated_results.csv

### ha-sRNA genome distribution analysis
mkdir -p ${EXP7_PATH}/genome/distribution
mkdir -p ${EXP7_PATH}/genome/enrichment

java -jar ${TOOL_GENOME_DISTRIBUTION} -bamMapping ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -windowLength 1000000 > ${EXP7_PATH}/genome/distribution/srna_genome_distribution-1Mb_znorm_results.csv
java -jar ${TOOL_GENOME_DISTRIBUTION} -bamMapping ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -windowLength 1000000 -readLength 22 > ${EXP7_PATH}/genome/distribution/srna_22nt_genome_distribution-1Mb_znorm_results.csv
java -jar ${TOOL_GENOME_DISTRIBUTION} -bamMapping ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -windowLength 1000000 -readLength 24 > ${EXP7_PATH}/genome/distribution/srna_24nt_genome_distribution-1Mb_znorm_results.csv

java -jar -Xmx${MAX_RAM} ${TOOL_GENOME_ENRICHMENT} -foldEnrichment 2 -bootstrap 10000 -bamMappingFile ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -srnaIndicesFile ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv -readLength 22 -windowLength 1000000 > ${EXP7_PATH}/genome/enrichment/mph_gy_positive_22nt_srna_genome_distribution_1Mb_z-norm_bootstrap_10000_results_2fold.csv
java -jar -Xmx${MAX_RAM} ${TOOL_GENOME_ENRICHMENT} -foldEnrichment 2 -bootstrap 10000 -bamMappingFile ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -srnaIndicesFile ${EXP6_PATH}/association/mph_gy_pos_expr0.5_fc2.csv -readLength 24 -windowLength 1000000 > ${EXP7_PATH}/genome/enrichment/mph_gy_positive_24nt_srna_genome_distribution_1Mb_z-norm_bootstrap_10000_results_2fold.csv
java -jar -Xmx${MAX_RAM} ${TOOL_GENOME_ENRICHMENT} -foldEnrichment 2 -bootstrap 10000 -bamMappingFile ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -srnaIndicesFile ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv -readLength 22 -windowLength 1000000 > ${EXP7_PATH}/genome/enrichment/mph_gy_negative_22nt_srna_genome_distribution_1Mb_z-norm_bootstrap_10000_results_2fold.csv
java -jar -Xmx${MAX_RAM} ${TOOL_GENOME_ENRICHMENT} -foldEnrichment 2 -bootstrap 10000 -bamMappingFile ${EXP3_PATH}/mapping/srna_heterosis_zmb73_refgen4.sorted.bam -srnaIndicesFile ${EXP6_PATH}/association/mph_gy_neg_expr0.5_fc2.csv -readLength 24 -windowLength 1000000 > ${EXP7_PATH}/genome/enrichment/mph_gy_negative_24nt_srna_genome_distribution_1Mb_z-norm_bootstrap_10000_results_2fold.csv

