package hybridcharacteristicassociationdatabase;

public enum HybridCharacteristic {
    HYBRID_PERFORMANCE, MID_PARENT_PERFORMANCE, MID_PARENT_PERFORMANCE_GAIN, BEST_PARENT_PERFORMANCE, BEST_PARENT_PERFORMANCE_GAIN, MID_PARENT_HETEROSIS, BEST_PARENT_HETEROSIS, SCA
}
